version = 1

exclude_patterns = ["static/"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "isort"